bar {
    position bottom
    status_command i3status
    font pango:JetBrainsMono Nerd Font SemiBold 11

    colors {
        background #000000cc
        statusline #e3e3d7
        separator  #909284

        focused_workspace #bacf83 #bacf83 #273500

        active_workspace #c3caaa #c3caaa #2d331c

        inactive_workspace #12140d #12140d #e3e3d7

        urgent_workspace #ffb4ab #ffb4ab #690005
    }
}
