#################################
#            Animation          #
#################################
animations = true;
animation-stiffness-in-tag = 125;
animation-stiffness-tag-change = 90.0;
animation-window-mass = 0.4;
animation-dampening = 15;
animation-clamping = true;
animation-for-open-window = "zoom";
animation-for-unmap-window = "squeeze";
animation-for-transient-window = "slide-up";
animation-for-prev-tag = "minimize";
enable-fading-prev-tag = true;
animation-for-next-tag = "slide-in-center";
enable-fading-next-tag = true;

#################################
#              Fade             #
#################################
fading = true;
fade-in-step = 0.065;
fade-out-step = 0.085;
fade-delta = 8;

#################################
#             Corners           #
#################################
corner-radius = 00.0;
round-borders = 0;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Polybar'",
  "class_g = 'eww-bar'",
  "class_g = 'tint2'",
  "class_g = 'Dunst'",
];

#################################
#     Background-Blurring       #
#################################
blur: {
  method = "dual_kawase";
  strength = 1;
  background = false;
  background-frame = false;
  background-fixed = false;
}

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Polybar'",
  "class_g = 'eww-bar'",
  "class_g = 'tint2'",
  "class_g = 'slop'",
  "class_g = 'Dunst'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#   Transparency / Opacity      #
#################################
inactive-opacity = 0.75;
active-opacity = 1.0;
inactive-dim-fixed = true;

focus-exclude = [
  "class_g ?= 'i3lock'",
  "class_g ?= 'Dmenu'",
];

opacity-rule = [#
  "100:class_g = 'Polybar'",
  "100:class_g = 'eww-bar'",
  "100:class_g = 'tint2'",
  "95:class_g = 'dunst'",
  "100:window_type = 'dock'",
  "98:class_g = 'Geany'"
];

#################################
#          Wintypes              #
#################################
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.95; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.95; }
  dropdown_menu = { opacity = 0.95; }
};


#################################
#          Backend              #
#################################
backend = "glx";
vsync = true;
glx-no-stencil = true;
log-level = "info";
