-- return {
--   {
--     "catppuccin/nvim",
--     opts = {
--       transparent_background = true, -- disables setting the background color.
--       float = {
--         transparent = true, -- enable transparent floating windows
--         solid = false, -- use solid styling for floating windows, see |winborder|
--       },
--     },
--     {
--       "aileot/ex-colors.nvim",
--       lazy = true,
--       cmd = "ExColors",
--       ---@type ExColors.Config
--       opts = {},
--     },
--   },
-- }
return {}
