#!/usr/bin/env python3
"""Generate a Vesktop System24 palette from Quickshell Material colors.

This script reads the Material You color palette generated by Quickshell's
wallpaper pipeline and produces a CSS file that overrides System24 theme
variables. The result keeps Vesktop in sync with the current wallpaper.

IMPORTANT: The generated CSS uses higher specificity to override system24's
default colors which are defined in :root.
"""

from __future__ import annotations

import json
import os
from colorsys import rgb_to_hls, hls_to_rgb
from pathlib import Path
from typing import Dict, Tuple


COLOR_SOURCE = Path(
    os.environ.get(
        "QUICKSHELL_COLORS_JSON",
        "~/.local/state/quickshell/user/generated/colors.json",
    )
).expanduser()

OUTPUT_FILE = Path(
    os.environ.get(
        "SYSTEM24_PALETTE_CSS",
        "~/.config/vesktop/themes/system24.theme.css",
    )
).expanduser()

MIDNIGHT_OUTPUT_FILE = Path(
    os.environ.get(
        "MIDNIGHT_DMS_CSS",
        "~/.config/vesktop/themes/ii-midnight.theme.css",
    )
).expanduser()


def _resolve_output_files(env_var: str, default_path: Path) -> list[Path]:
    """Return a list of paths to write the theme to.

    Different builds/packaging may use different XDG config folder casing
    (e.g. ~/.config/vesktop vs ~/.config/Vesktop).
    If the env var is set, it remains authoritative.
    """

    explicit = os.environ.get(env_var)
    if explicit:
        return [Path(explicit).expanduser()]

    basename = default_path.name
    candidates = [
        Path(f"~/.config/vesktop/themes/{basename}").expanduser(),
        Path(f"~/.config/Vesktop/themes/{basename}").expanduser(),
    ]

    existing_dirs = [p for p in candidates if p.parent.exists()]
    if existing_dirs:
        return existing_dirs

    return [default_path]

# Template for the full theme file
THEME_TEMPLATE = '''/**
 * @name iNiR Material
 * @description Material Design Discord theme with Material You colors.
 * @author refact0r (system24 base), iNiR (Material adaptation)
 * @version 2.2.0
 * @source https://github.com/end-4/iNiR
 */

/*
 * Base theme import:
 * - Prefer a local copy if present (more reliable on flaky networks / CSP).
 * - Keep the remote import as fallback.
 */
@import url('system24.local.css');
@import url('https://refact0r.github.io/system24/build/system24.css');
@import url('https://fonts.googleapis.com/css2?family=Oxanium:wght@300;400;500;600;700&display=swap');

body {{
    --font: 'Oxanium';
    --code-font: 'Oxanium';
    font-weight: 400;
    letter-spacing: -0.02ch;
    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 2px;
    --border-hover-transition: 0.2s ease;
    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --top-bar-height: 36px;
    --top-bar-button-position: off;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;
    --custom-window-controls: off;
    --window-control-size: 14px;
    --custom-dms-icon: off;
    --dms-icon-svg-size: 90%;
    --dms-icon-color-before: var(--text-0);
    --dms-icon-color-after: var(--text-0);
    --custom-dms-background: color;
    --dms-background-color: var(--accent-2);
    --background-image: off;
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 0px;
    --bg-floating: var(--bg-1);
    --small-user-panel: on;
    --unrounding: off;
    --custom-spotify-bar: on;
    --ascii-titles: off;
    --ascii-loader: off;
    --panel-labels: off;
    --label-color: var(--text-4);
    --label-font-weight: 500;
}}

/* Material You Palette - Auto-generated */
{palette_css}

/* Material Design System */
'''

MIDNIGHT_THEME_TEMPLATE = '''/**
 * @name ii-midnight
 * @description dank-discord / midnight style theme using iNiR Material You colors.
 * @author iNiR (Material palette injection)
 * @version 2.2.0
 * @source https://github.com/end-4/iNiR
 */

/*
 * Base theme import:
 * - Prefer your local copy (if you have it in the same folder).
 * - Fallback to remote so the theme works on fresh installs.
 */
@import url('dank-discord.css');
@import url('https://refact0r.github.io/midnight-discord/build/midnight.css');

/* Material You Palette - Auto-generated */
{palette_css}

/*
 * Reduce hover/active highlight.
 * The base theme can still style hover states, but the strong accent overlay is removed.
 */
:root, :root:root, body, #app-mount {{
    --hover: transparent;
    --active: transparent;
    --active-2: transparent;
    --message-hover: transparent;
    --border-hover: var(--border);
    --border-light: var(--border);
    --button-border: var(--border);
}}
'''


def _ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _load_colors() -> Dict[str, str]:
    if not COLOR_SOURCE.exists():
        raise FileNotFoundError(
            f"Material colors file not found: {COLOR_SOURCE}. "
            "Ensure switchwall.sh has been executed successfully."
        )
    with COLOR_SOURCE.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    return {k: v.lower() for k, v in data.items()}


def _hex_to_rgb(color: str) -> Tuple[int, int, int]:
    color = color.lstrip("#")
    return tuple(int(color[i : i + 2], 16) for i in range(0, 6, 2))


def _rgb_to_hex(rgb) -> str:
    r, g, b = (max(0, min(int(round(v)), 255)) for v in rgb)
    return f"#{r:02x}{g:02x}{b:02x}"


def _mix(color_a: str, color_b: str, weight: float) -> str:
    ra, ga, ba = _hex_to_rgb(color_a)
    rb, gb, bb = _hex_to_rgb(color_b)
    mixed = (
        ra * (1 - weight) + rb * weight,
        ga * (1 - weight) + gb * weight,
        ba * (1 - weight) + bb * weight,
    )
    return _rgb_to_hex(mixed)


def _adjust_lightness(color: str, delta: float) -> str:
    r, g, b = (c / 255.0 for c in _hex_to_rgb(color))
    h, l, s = rgb_to_hls(r, g, b)
    l = max(0.0, min(1.0, l + delta))
    r2, g2, b2 = hls_to_rgb(h, l, s)
    return _rgb_to_hex((r2 * 255, g2 * 255, b2 * 255))


def _rgba(color: str, alpha: float) -> str:
    r, g, b = _hex_to_rgb(color)
    return f"rgba({r}, {g}, {b}, {alpha:.2f})"


def _build_palette(colors: Dict[str, str]) -> Dict[str, str]:
    """Build the complete system24 color palette from Material You colors."""
    primary = colors["primary"]
    secondary = colors["secondary"]
    tertiary = colors["tertiary"]
    error = colors["error"]
    surface = colors["surface"]
    surface_low = colors["surface_container_low"]
    surface_std = colors["surface_container"]
    surface_high = colors["surface_container_high"]
    surface_highest = colors["surface_container_highest"]
    outline = colors["outline"]
    on_surface = colors["on_surface"]
    on_surface_variant = colors["on_surface_variant"]
    on_primary = colors["on_primary"]

    palette: Dict[str, str] = {}

    # Enable custom colors
    palette["--colors"] = "on"

    # === TEXT COLORS ===
    # --text-0: text on colored elements (like buttons)
    palette["--text-0"] = on_primary
    # --text-1: bright white text
    palette["--text-1"] = on_surface
    # --text-2: headings and important text
    palette["--text-2"] = _mix(on_surface, on_surface_variant, 0.2)
    # --text-3: normal text
    palette["--text-3"] = _mix(on_surface, on_surface_variant, 0.4)
    # --text-4: icon buttons and channels
    palette["--text-4"] = on_surface_variant
    # --text-5: muted channels/chats and timestamps
    palette["--text-5"] = outline

    # === BACKGROUND COLORS ===
    # --bg-4: main background (darkest)
    palette["--bg-4"] = surface
    # --bg-3: spacing, secondary elements
    palette["--bg-3"] = surface_low
    # --bg-2: dark buttons
    palette["--bg-2"] = surface_std
    # --bg-1: dark buttons when clicked
    palette["--bg-1"] = surface_high
    # --bg-floating: floating panels
    palette["--bg-floating"] = surface_highest

    # === INTERACTION STATES ===
    palette["--hover"] = _rgba(primary, 0.10)
    palette["--active"] = _rgba(primary, 0.20)
    palette["--active-2"] = _rgba(primary, 0.30)
    palette["--message-hover"] = _rgba(primary, 0.08)

    # === ACCENT COLORS (based on primary) ===
    palette["--accent-1"] = _adjust_lightness(primary, 0.10)
    palette["--accent-2"] = primary
    palette["--accent-3"] = _adjust_lightness(primary, -0.05)
    palette["--accent-4"] = _adjust_lightness(primary, -0.10)
    palette["--accent-5"] = _adjust_lightness(primary, -0.15)
    palette["--accent-new"] = primary  # Use accent color instead of error for NEW badge

    # === MENTION/REPLY GRADIENTS ===
    palette["--mention"] = (
        f"linear-gradient(to right, "
        f"color-mix(in hsl, {primary}, transparent 70%) 40%, transparent)"
    )
    palette["--mention-hover"] = (
        f"linear-gradient(to right, "
        f"color-mix(in hsl, {primary}, transparent 85%) 40%, transparent)"
    )
    palette["--reply"] = (
        f"linear-gradient(to right, "
        f"color-mix(in hsl, {on_surface_variant}, transparent 85%) 40%, transparent)"
    )
    palette["--reply-hover"] = (
        f"linear-gradient(to right, "
        f"color-mix(in hsl, {on_surface_variant}, transparent 92%) 40%, transparent)"
    )

    # === STATUS COLORS ===
    palette["--online"] = tertiary
    palette["--dnd"] = error
    palette["--idle"] = secondary
    palette["--streaming"] = _adjust_lightness(tertiary, 0.10)
    palette["--offline"] = on_surface_variant

    # === BORDER COLORS ===
    palette["--border-light"] = _rgba(outline, 0.15)
    palette["--border"] = _rgba(outline, 0.30)
    palette["--border-hover"] = primary
    palette["--button-border"] = _rgba(outline, 0.12)

    # === BASE COLOR LADDERS ===
    # These are used throughout system24 for various UI elements
    
    def make_ladder(base: str) -> list:
        """Create 5-step color ladder from base color."""
        return [
            _adjust_lightness(base, 0.15),
            _adjust_lightness(base, 0.08),
            base,
            _adjust_lightness(base, -0.08),
            _adjust_lightness(base, -0.15),
        ]

    # Red ladder (from error color)
    for i, color in enumerate(make_ladder(error), 1):
        palette[f"--red-{i}"] = color

    # Green ladder (from tertiary - usually green-ish)
    for i, color in enumerate(make_ladder(tertiary), 1):
        palette[f"--green-{i}"] = color

    # Blue ladder (from secondary)
    for i, color in enumerate(make_ladder(secondary), 1):
        palette[f"--blue-{i}"] = color

    # Yellow ladder (mix of primary and tertiary for warm tone)
    yellow_base = _mix(primary, tertiary, 0.3)
    yellow_base = _adjust_lightness(yellow_base, 0.05)
    for i, color in enumerate(make_ladder(yellow_base), 1):
        palette[f"--yellow-{i}"] = color

    # Purple ladder (mix of primary and secondary)
    purple_base = _mix(primary, secondary, 0.5)
    for i, color in enumerate(make_ladder(purple_base), 1):
        palette[f"--purple-{i}"] = color

    # Orange ladder (warmer version of primary)
    orange_base = _mix(primary, error, 0.3)
    for i, color in enumerate(make_ladder(orange_base), 1):
        palette[f"--orange-{i}"] = color

    # === DISCORD BRAND OVERRIDES ===
    # These override Discord's default blurple with our accent
    palette["--brand-360"] = _adjust_lightness(primary, 0.08)
    palette["--brand-400"] = _adjust_lightness(primary, 0.04)
    palette["--brand-500"] = primary
    palette["--brand-560"] = _adjust_lightness(primary, -0.06)
    palette["--brand-600"] = _adjust_lightness(primary, -0.12)

    return palette


def _build_palette_css(palette: Dict[str, str]) -> str:
    palette_lines = [":root, :root:root, body, #app-mount {"]
    for key in sorted(palette.keys()):
        palette_lines.append(f"    {key}: {palette[key]};")
    palette_lines.append("}")
    return "\n".join(palette_lines)


def _write_palette(palette: Dict[str, str]) -> None:
    """Write the complete theme files with embedded palette."""
    palette_css = _build_palette_css(palette)

    system24_outputs = _resolve_output_files("SYSTEM24_PALETTE_CSS", OUTPUT_FILE)
    midnight_outputs = _resolve_output_files("MIDNIGHT_DMS_CSS", MIDNIGHT_OUTPUT_FILE)

    for out in (system24_outputs + midnight_outputs):
        _ensure_parent(out)

    system24_content = THEME_TEMPLATE.format(palette_css=palette_css)
    midnight_content = MIDNIGHT_THEME_TEMPLATE.format(palette_css=palette_css)

    for out in system24_outputs:
        with out.open("w", encoding="utf-8") as fh:
            fh.write(system24_content)
        print(f"Generated: {out}")

    for out in midnight_outputs:
        with out.open("w", encoding="utf-8") as fh:
            fh.write(midnight_content)
        print(f"Generated: {out}")


def main() -> None:
    try:
        colors = _load_colors()
    except FileNotFoundError as exc:
        print(f"Error: {exc}")
        return

    palette = _build_palette(colors)
    _write_palette(palette)


if __name__ == "__main__":
    main()
