[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "any", "--transition-fps", "60"]
set = true

[templates.mango]
input_path = '~/.config/matugen/templates/mango.conf'
output_path = '~/.config/mango/colors.conf'
post_hook = "sed -i 's/0x#\\([0-9a-fA-F]\\{6\\}\\)ff/0x\\1ff/g' ~/.config/mango/colors.conf && mmsg -d reload_config"

[templates.xwallpaper]
input_path = '~/.config/matugen/templates/betterlockscreen-dummy.txt'
output_path = '~/.config/dummy/dummy.txt'
post_hook = 'xwallpaper --zoom ~/.config/hypr/current_wallpaper'

[templates.oxwm]
input_path = '~/.config/matugen/templates/oxwm-colors.lua'
output_path = '~/.config/oxwm/matugen.lua'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.noctalia]
input_path = '~/.config/matugen/templates/noctalia.json'
output_path = '~/.config/noctalia/colors.json'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.dwl]
input_path = '~/.config/matugen/templates/config.def.h'
output_path = '~/.config/dwldotfiles/dwl/config.def.h'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.cava]
input_path = '~/.config/matugen/templates/matugen-cava'
output_path = '~/.config/cava/config'
post_hook = 'pgrep -x cava >/dev/null || cava &; pkill -USR1 cava'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spotify-colors.ini'
output_path = '~/.config/spicetify/Themes/text/color.ini'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/matugen.css'

[templates.nwg-dock-hyprland]
input_path = '~/.config/matugen/templates/nwg-dock-colors.css'
output_path = '~/.config/nwg-dock-hyprland/colors.css'
post_hook = '$HOME/.config/hypr/scripts/dockrestart.sh'

[templates.dummy]
input_path = '~/.config/matugen/templates/fish-colors.fish'
output_path = '~/.config/fish/conf.d/matugen.fish'

[templates.sway]
input_path = '~/.config/matugen/templates/sway.conf'
output_path = '~/.config/sway/bar.conf'
post_hook = 'swaymsg reload'

[templates.windowsway]
input_path = '~/.config/matugen/templates/windowsway.conf'
output_path = '~/.config/sway/window.conf'
post_hook = 'swaymsg reload'

[templates.mwc]
input_path = '~/.config/matugen/templates/mwc.conf'
output_path = '~/.config/mwc/mwc.conf'#

[templates.niri]
input_path = '~/.config/matugen/templates/colors.kdl'
output_path = '~/.config/niri/config.kdl'
