# Auto-generated by matugen – DO NOT EDIT

set -g MAT_BG        "#0f1417"
set -g MAT_SURFACE   "#0f1417"
set -g MAT_PRIMARY   "#8bd0ef"
set -g MAT_SECONDARY "#b4cad6"
set -g MAT_TERTIARY  "#c6c2ea"
set -g MAT_ERROR     "#ffb4ab"
set -g MAT_OUTLINE   "#8a9297"
set -g MAT_ON_SURF   "#dfe3e7"
