rootcolor           = 0x{{ colors.surface.default.hex }}ff
bordercolor         = 0x{{ colors.outline.default.hex }}ff
focuscolor          = 0x{{ colors.primary.default.hex }}ff
maximizescreencolor = 0x{{ colors.tertiary.default.hex }}ff
urgentcolor         = 0x{{ colors.error.default.hex }}ff
scratchpadcolor     = 0x{{ colors.secondary_container.default.hex }}ff
globalcolor         = 0x{{ colors.secondary.default.hex }}ff
overlaycolor        = 0x{{ colors.primary_container.default.hex }}ff
