bar {
    position bottom
    status_command i3status
    font pango:JetBrainsMono Nerd Font SemiBold 11

    colors {
        background #000000cc
        statusline {{colors.on_background.default.hex}}
        separator  {{colors.outline.default.hex}}

        focused_workspace {{colors.primary.default.hex}} {{colors.primary.default.hex}} {{colors.on_primary.default.hex}}

        active_workspace {{colors.secondary.default.hex}} {{colors.secondary.default.hex}} {{colors.on_secondary.default.hex}}

        inactive_workspace {{colors.surface.default.hex}} {{colors.surface.default.hex}} {{colors.on_surface.default.hex}}

        urgent_workspace {{colors.error.default.hex}} {{colors.error.default.hex}} {{colors.on_error.default.hex}}
    }
}
