default_border pixel 2
default_floating_border pixel 2

gaps inner 8
gaps outer 12

client.focused           {{colors.primary.default.hex}} {{colors.primary.default.hex}} {{colors.on_primary.default.hex}} {{colors.primary.default.hex}}
client.unfocused         {{colors.surface.default.hex}} {{colors.surface.default.hex}} {{colors.outline.default.hex}} {{colors.surface.default.hex}}
client.urgent            {{colors.error.default.hex}} {{colors.error.default.hex}} {{colors.on_error.default.hex}} {{colors.error.default.hex}}

# waybar blur
layer_effects "waybar" blur enable; shadows disable;
layer_effects "gtk-layer-shell" blur enable; shadows enable; corner_radius 4
layer_effects "rofi" blur enable; shadows enable; corner_radius 4
layer_effects "avizo" blur enable; corner_radius 4

smart_corner_radius enable
corner_radius 4
shadows enable
shadows_on_csd enable
shadow_blur_radius 20
default_dim_inactive 0.13

## blur
blur enable
blur_xray disable
blur_passes 4
blur_radius 4
