windowrule {
  name = float-pavu
  match:class = org.pulseaudio.pavucontrol
  float = on
  size = 50% 60%
}

windowrule {
  name = suppress-maximize
  match:class = .*
  suppress_event = maximize
}

windowrule {
  name = xwayland-dragfix
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false
  no_focus = on
}

